# *******************************************************************
# Copy this file's contents into config.local.yml, and edit it to your needs
# *******************************************************************

# The bot token
TOKEN: BOT-TOKEN-HERE

# The ID of the discord user that'll be able to reload the bot's slash commands
ADMIN_ID: ADMIN-ID-HERE
